version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
